# Generated by Django 6.0.6 on 2026-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualinspection',
            name='category',
            field=models.CharField(help_text='Ej., Frenos, Neumáticos, Motor', max_length=100),
        ),
        migrations.AlterField(
            model_name='visualinspection',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Bien (Verde)'), ('YELLOW', 'Advertencia (Amarillo)'), ('RED', 'Crítico (Rojo)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='fuel_level',
            field=models.IntegerField(help_text='Porcentaje de nivel de combustible (0-100)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20),
        ),
    ]
