# Generated by Django 6.0.6 on 2026-06-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_visualinspection_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
