# Generated by Django 6.0.6 on 2026-06-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_servicecategory_stocktransaction_notes_and_more'),
        ('operations', '0004_client_workorder_mechanic_vehicle_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.service'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
