# Generated by Django 6.0.6 on 2026-06-30 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_workorderitem_service_alter_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{7,20}$', 'Ingrese un número de teléfono válido.')]),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='fuel_level',
            field=models.IntegerField(help_text='Porcentaje de nivel de combustible (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
