# Generated by Django 6.0.6 on 2026-06-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_vehicle_owner_name_remove_vehicle_owner_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MecanIA', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workshop_logo/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
