# Generated by Django 6.0.6 on 2026-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_workshopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Color del vehículo', max_length=30, null=True),
        ),
    ]
