# Generated by Django 6.0.6 on 2026-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_displacement',
            field=models.CharField(blank=True, help_text='Cilindrada (ej: 1.6, 2.0L)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Número de Motor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GASOLINE', 'Gasolina'), ('DIESEL', 'Diesel'), ('HYBRID', 'Híbrido'), ('ELECTRIC', 'Eléctrico'), ('GNC_GLP', 'Gas (GNC/GLP)')], default='GASOLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(blank=True, help_text='Kilometraje inicial', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automática'), ('CVT', 'CVT'), ('DCT', 'Doble Embrague')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Número VIN (Chasis)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='additional_findings',
            field=models.TextField(blank=True, help_text='Hallazgos o problemas adicionales encontrados por el mecánico', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='desired_service',
            field=models.TextField(blank=True, help_text='Servicio que desea realizar', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='findings_approved',
            field=models.BooleanField(default=False, help_text='¿Los hallazgos adicionales fueron aprobados por el cliente?'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas reportados', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='visit_reason',
            field=models.TextField(blank=True, help_text='Motivo de la visita', null=True),
        ),
    ]
