# Generated by Django 6.0.6 on 2026-07-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_vehicle_license_plate_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsettings',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Enlace de ubicación en Google Maps', null=True),
        ),
    ]
