# Generated by Django 6.0.6 on 2026-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_workshopsettings_google_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo del taller en formato Base64', null=True),
        ),
    ]
