# Generated by Django 6.0.6 on 2026-07-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_workshopsettings_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visualinspection',
            name='items_json',
            field=models.JSONField(blank=True, default=dict, help_text='Resultados de la inspección por partes en formato JSON'),
        ),
        migrations.AddField(
            model_name='visualinspection',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualinspection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visualinspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visualinspection',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_inspections', to='operations.vehicle'),
        ),
        migrations.AlterField(
            model_name='visualinspection',
            name='category',
            field=models.CharField(blank=True, help_text='Ej., Frenos, Neumáticos, Motor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visualinspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualinspection',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='operations.workorder'),
        ),
    ]
