# Generated by Django 6.0.6 on 2026-07-01 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_visualinspection_items_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('OIL_CHANGE', 'Cambio de Aceite'), ('FILTER_CHANGE', 'Cambio de Filtros'), ('BELT_CHANGE', 'Cambio de Correas'), ('BRAKE_SERVICE', 'Servicio de Frenos'), ('TIRE_ROTATION', 'Rotación de Neumáticos'), ('COOLANT_FLUSH', 'Cambio de Refrigerante'), ('TRANSMISSION_SERVICE', 'Servicio de Transmisión'), ('SPARK_PLUGS', 'Cambio de Bujías'), ('TIMING_BELT', 'Correa de Distribución'), ('GENERAL_SERVICE', 'Servicio General'), ('OTHER', 'Otro')], default='GENERAL_SERVICE', max_length=30)),
                ('description', models.TextField(help_text='Descripción de lo realizado')),
                ('mileage', models.IntegerField(help_text='Kilometraje al momento de la mantención', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_performed', models.DateField(help_text='Fecha de la mantención')),
                ('product_details', models.TextField(blank=True, help_text='Detalles del producto usado (marca, especificación, viscosidad, etc.)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de la mantención', max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Quién realizó el trabajo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='operations.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='operations.workorder')),
            ],
            options={
                'verbose_name': 'Registro de Mantención',
                'verbose_name_plural': 'Registros de Mantención',
                'ordering': ['-date_performed'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('OIL_CHANGE', 'Cambio de Aceite'), ('FILTER_CHANGE', 'Cambio de Filtros'), ('BELT_CHANGE', 'Cambio de Correas'), ('BRAKE_SERVICE', 'Servicio de Frenos'), ('TIRE_ROTATION', 'Rotación de Neumáticos'), ('COOLANT_FLUSH', 'Cambio de Refrigerante'), ('TRANSMISSION_SERVICE', 'Servicio de Transmisión'), ('SPARK_PLUGS', 'Cambio de Bujías'), ('TIMING_BELT', 'Correa de Distribución'), ('GENERAL_SERVICE', 'Servicio General'), ('OTHER', 'Otro')], default='GENERAL_SERVICE', max_length=30)),
                ('description', models.CharField(help_text='Descripción breve (ej: Próximo cambio de aceite)', max_length=255)),
                ('due_mileage', models.IntegerField(blank=True, help_text='Kilometraje al que se debe realizar', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite para realizar', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('NOTIFIED', 'Notificado'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido')], default='PENDING', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Cuándo se notificó al cliente', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='operations.vehicle')),
            ],
            options={
                'verbose_name': 'Mantención Programada',
                'verbose_name_plural': 'Mantenciones Programadas',
                'ordering': ['due_date', 'due_mileage'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la parte (ej: Filtro de aceite)', max_length=200)),
                ('oem_number', models.CharField(help_text='Número OEM del fabricante', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Marca del repuesto (ej: Mann-Filter)', max_length=100)),
                ('category', models.CharField(choices=[('FILTER', 'Filtro'), ('BELT', 'Correa'), ('BRAKE', 'Frenos'), ('SUSPENSION', 'Suspensión'), ('ENGINE', 'Motor'), ('ELECTRICAL', 'Eléctrico'), ('BODY', 'Carrocería'), ('COOLING', 'Refrigeración'), ('TRANSMISSION', 'Transmisión'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('installed_at', models.DateField(help_text='Fecha de instalación')),
                ('installed_mileage', models.IntegerField(blank=True, help_text='Kilometraje al momento de instalar', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='operations.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_parts', to='operations.workorder')),
            ],
            options={
                'verbose_name': 'Parte de Vehículo',
                'verbose_name_plural': 'Partes de Vehículos',
                'ordering': ['-installed_at'],
            },
        ),
    ]
