# Generated by Django 6.0.6 on 2026-07-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_maintenancerecord_scheduledmaintenance_vehiclepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pin_hash',
            field=models.CharField(blank=True, default='', help_text='PIN de 4 dígitos hasheado para acceso al portal de clientes.', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_enabled',
            field=models.BooleanField(default=False, help_text='Indica si el cliente tiene acceso al portal.'),
        ),
    ]
