# Generated by Django 6.0.6 on 2026-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_client_portal_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Nombre del archivo (ej: creds.json o pre-key-*)', max_length=255, unique=True)),
                ('data', models.TextField(help_text='Contenido serializado del archivo (Base64 o JSON texto)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
