# Generated by Django 6.0.6 on 2026-07-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_whatsapp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Flujo')),
                ('trigger_type', models.CharField(choices=[('welcome', 'Mensaje de Bienvenida (Welcome)'), ('keyword', 'Palabra Clave (Keyword)'), ('default', 'Respuesta por Defecto (Fallback)')], default='keyword', max_length=20)),
                ('keywords', models.CharField(blank=True, help_text='Lista de palabras separadas por comas. Ej: precio, cotizar, costo, valor', max_length=255, verbose_name='Palabras Clave')),
                ('action_type', models.CharField(choices=[('static', 'Mensaje de Texto Estático'), ('ai_assistant', 'Agente de IA (GPT)'), ('portal_link', 'Enviar Enlace de Acceso al Portal'), ('human_transfer', 'Derivar a Humano (Notificar / Pausar Asistente)')], default='static', max_length=20)),
                ('response_text', models.TextField(blank=True, default='', help_text='El texto estático para responder, o las instrucciones de comportamiento personalizadas para el agente de IA.', verbose_name='Mensaje de Respuesta / Instrucciones de IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flujo de WhatsApp',
                'verbose_name_plural': 'Flujos de WhatsApp',
                'ordering': ['trigger_type', 'name'],
            },
        ),
    ]
