# Generated by Django 6.0.6 on 2026-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_whatsappflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsettings',
            name='assistant_prompt',
            field=models.TextField(blank=True, default='', help_text='Prompt del sistema para el comportamiento general del asistente de IA.'),
        ),
    ]
