# Generated by Django 6.0.6 on 2026-07-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_workshopsettings_assistant_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Número de teléfono del remitente o destinatario.', max_length=50)),
                ('sender', models.CharField(choices=[('client', 'Cliente'), ('assistant', 'Asistente IA'), ('operator', 'Operador Humano')], default='client', max_length=20)),
                ('text', models.TextField(help_text='Contenido del mensaje.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='operations.client')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
                'ordering': ['timestamp'],
            },
        ),
    ]
