# Generated by Django 6.0.6 on 2026-07-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bot_silenced_until',
            field=models.DateTimeField(blank=True, help_text='Silencia el asistente de IA para este cliente hasta esta fecha/hora.', null=True),
        ),
    ]
