# Generated by Django 6.0.6 on 2026-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_client_bot_silenced_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsettings',
            name='admin_whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp del Administrador para notificaciones de cierre de caja (ej: +56912345678)', max_length=20),
        ),
    ]
