# Generated by Django 6.0.6 on 2026-07-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_workshopsettings_admin_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo adjunto', upload_to='work_orders/attachments/')),
                ('file_name', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.workorder')),
            ],
        ),
    ]
