# Generated by Django 6.0.6 on 2026-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_fix_client_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
