# Generated by Django 6.0.6 on 2026-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_cleanup_lid_whatsapp_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappflow',
            name='buttons',
            field=models.TextField(blank=True, default='', help_text='Lista de opciones o botones de respuesta rápida para el cliente, una por línea.', verbose_name='Opciones / Botones (Uno por línea)'),
        ),
    ]
