# Generated by Django 6.0.6 on 2026-07-14 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_whatsappflow_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappflow',
            name='button_routes',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeo de opciones a IDs de flujos siguientes'),
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='canvas_position',
            field=models.JSONField(blank=True, default=dict, help_text='Posición X, Y en el canvas UI'),
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='next_step',
            field=models.ForeignKey(blank=True, help_text='Flujo siguiente por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_static_routes', to='operations.whatsappflow'),
        ),
    ]
