# Generated by Django 6.0.6 on 2026-07-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_whatsappflow_button_routes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Artículo')),
                ('content', models.TextField(verbose_name='Contenido (Markdown/HTML)')),
                ('author', models.CharField(default='Equipo MecanIA', max_length=100, verbose_name='Autor')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen de Portada')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post de Blog',
                'verbose_name_plural': 'Posts de Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Oferta')),
                ('description', models.TextField(verbose_name='Descripción o Detalles')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen Promocional')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oferta del Portal',
                'verbose_name_plural': 'Ofertas del Portal',
                'ordering': ['-created_at'],
            },
        ),
    ]
