# Generated by Django 6.0.6 on 2026-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_portalblogpost_portaloffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalblogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='portaloffer',
            name='image_url',
        ),
        migrations.AddField(
            model_name='portalblogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portal/blogs/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='portaloffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portal/offers/', verbose_name='Imagen Promocional'),
        ),
    ]
