# Generated by Django 6.0.6 on 2026-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_remove_portalblogpost_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalblogpost',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen de Portada (Base64 u URL)'),
        ),
        migrations.AlterField(
            model_name='portaloffer',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen Promocional (Base64 u URL)'),
        ),
    ]
