# Generated by Django 6.0.6 on 2026-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_alter_portalblogpost_image_alter_portaloffer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento o Manual')),
                ('category', models.CharField(choices=[('manual', 'Manual de Taller / Reparación'), ('filters', 'Catálogo de Filtros y Fluidos'), ('diagram', 'Diagrama Eléctrico / Pinout'), ('torques', 'Torques y Especificaciones Técnicas'), ('maintenance', 'Guías de Mantenimiento / Pautas'), ('other', 'Otra Documentación Técnica')], default='manual', max_length=30, verbose_name='Categoría Técnica')),
                ('make', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Vehículo (ej. Toyota)')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo (ej. RAV4)')),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='Año Desde (ej. 2015)')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Año Hasta (ej. 2022)')),
                ('engine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor (ej. 2.0 3ZR-FE / 1.6 HDI)')),
                ('tags', models.CharField(blank=True, default='', help_text='Separadas por comas (ej. correa distribucion, torque culata, mann hu711/5x)', max_length=255, verbose_name='Etiquetas o Palabras Clave')),
                ('content_text', models.TextField(help_text='Información, especificaciones y notas legibles por la IA para dar respuestas exactas.', verbose_name='Contenido Técnico / Extracto de Texto')),
                ('file_data', models.TextField(blank=True, help_text='Opcional. PDF o Imagen del diagrama/manual.', null=True, verbose_name='Archivo Adjunto (Base64 u URL)')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Original del Archivo')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, la IA leerá este documento para responder consultas.', verbose_name='Activo para IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Conocimiento Técnico',
                'verbose_name_plural': 'Documentos de Conocimiento Técnico',
                'ordering': ['-created_at'],
            },
        ),
    ]
