# Generated by Django 6.0.6 on 2026-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado al Cliente'), ('PAID', 'Pagado'), ('VOID', 'Anulado')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta de Crédito/Débito'), ('TRANSFER', 'Transferencia Bancaria')], max_length=20),
        ),
    ]
