# Generated by Django 6.0.6 on 2026-06-29 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_method_payment_payment_method_and_more'),
        ('inventory', '0004_servicecategory_stocktransaction_notes_and_more'),
        ('operations', '0005_workorderitem_service_alter_workorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de los pagos/abonos registrados contra esta factura.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente de la venta de mostrador. En ventas anónimas puede quedar vacío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sale_invoices', to='operations.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('WORK_ORDER', 'Orden de Trabajo'), ('COUNTER_SALE', 'Venta de Mostrador')], default='WORK_ORDER', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado al Cliente'), ('PARTIALLY_PAID', 'Pago Parcial (Abono)'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado'), ('VOID', 'Anulado')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='operations.workorder'),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Se completa automáticamente desde el producto/servicio si se deja vacío.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.service')),
            ],
        ),
    ]
