# Generated by Django 6.0.6 on 2026-07-06 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_cash_register_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT de la empresa proveedora', max_length=20, unique=True)),
                ('company_name', models.CharField(help_text='Razón Social / Nombre', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Nombre del vendedor / contacto', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono del vendedor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Sesión de caja activa en el turno de trabajo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.cashregistersession')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número / Folio de la Factura', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('emission_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xml_or_pdf_data', models.TextField(blank=True, help_text='Datos crudos JSON extraídos del DTE o PDF')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIALLY_PAID', 'Pago Parcial'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CHECK', 'Cheque'), ('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('OTHER', 'Otro')], default='CHECK', max_length=20)),
                ('document_number', models.CharField(blank=True, help_text='Número de cheque o código de operación', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(help_text='Fecha programada de cobro/pago')),
                ('bank', models.CharField(blank=True, help_text='Banco emisor (para cheques)', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Cobro'), ('PAID', 'Cobrado/Pagado'), ('BOUNCED', 'Rebotado'), ('CANCELLED', 'Anulado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='finance.supplierinvoice')),
            ],
        ),
    ]
