# Generated by Django 6.0.6 on 2026-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_supplier_cashmovement_supplierinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento global aplicado a la factura.', max_digits=12),
        ),
    ]
