# Generated by Django 6.0.6 on 2026-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Entrada de Stock'), ('OUT', 'Salida de Stock (Usado en OT)')], max_length=10),
        ),
    ]
