# Generated by Django 6.0.6 on 2026-06-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stocktransaction_transaction_type'),
        ('operations', '0003_vehicle_owner_name_vehicle_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='operations.workorder'),
        ),
    ]
