# Generated by Django 6.0.6 on 2026-06-30 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_barcode_product_cost_price_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='Cantidad de veces que se ha vendido este producto'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Si es verdadero, el precio y stock dependen de los productos asociados.'),
        ),
        migrations.AddField(
            model_name='service',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='Cantidad de veces que se ha vendido este servicio'),
        ),
        migrations.CreateModel(
            name='ServiceBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_usages', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='inventory.service')),
            ],
            options={
                'verbose_name': 'Item de Servicio Compuesto',
                'verbose_name_plural': 'Items de Servicio Compuesto',
                'unique_together': {('service', 'product')},
            },
        ),
    ]
