# Generated by Django 6.0.6 on 2026-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_image_product_sales_count_service_is_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Categoría'),
        ),
    ]
