# Generated by Django 6.0.6 on 2026-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Neto'),
        ),
        migrations.AddField(
            model_name='service',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Neto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (IVA incluido)'),
        ),
    ]
