# Generated by Django on manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
