# Generated by Django 6.0.6 on 2026-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_net_price_service_net_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='block_sale_without_stock',
            field=models.BooleanField(default=False, verbose_name='Bloquear venta sin stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
